name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Next Tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        WITH_V: true
        DRY_RUN: true
      id: next_tag
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and Publish package
      run: mvn --batch-mode deploy -Drevision=${{ steps.next_tag.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        args: ${{ steps.next_tag.outputs.new_tag }}
    - name: Tagging release
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        WITH_V: true
